-- ==========================================================
-- RETAIL SALES ANALYTICS PROJECT
-- Employee Analysis
-- ==========================================================

--------------------------------------------------------------
-- 1. Total Employees
--------------------------------------------------------------
SELECT COUNT(*) AS total_employees
FROM employees;

--------------------------------------------------------------
-- 2. Employees in Each Store
--------------------------------------------------------------
SELECT
    s.store_name,
    COUNT(e.employee_id) AS total_employees
FROM stores s
LEFT JOIN employees e
ON s.store_id = e.store_id
GROUP BY s.store_id, s.store_name
ORDER BY total_employees DESC;

--------------------------------------------------------------
-- 3. Orders Handled by Each Employee
--------------------------------------------------------------
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    COUNT(o.order_id) AS total_orders
FROM employees e
LEFT JOIN orders o
ON e.employee_id = o.employee_id
GROUP BY
    e.employee_id,
    e.first_name,
    e.last_name
ORDER BY total_orders DESC;

--------------------------------------------------------------
-- 4. Revenue Generated by Each Employee
--------------------------------------------------------------
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    ROUND(SUM(p.amount),2) AS revenue
FROM employees e
JOIN orders o
ON e.employee_id = o.employee_id
JOIN payments p
ON o.order_id = p.order_id
WHERE p.payment_status='Paid'
GROUP BY
    e.employee_id,
    e.first_name,
    e.last_name
ORDER BY revenue DESC;

--------------------------------------------------------------
-- 5. Average Order Value per Employee
--------------------------------------------------------------
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    ROUND(AVG(p.amount),2) AS average_order_value
FROM employees e
JOIN orders o
ON e.employee_id = o.employee_id
JOIN payments p
ON o.order_id = p.order_id
WHERE p.payment_status='Paid'
GROUP BY
    e.employee_id,
    e.first_name,
    e.last_name
ORDER BY average_order_value DESC;

--------------------------------------------------------------
-- 6. Top 10 Employees by Revenue
--------------------------------------------------------------
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    ROUND(SUM(p.amount),2) AS revenue
FROM employees e
JOIN orders o
ON e.employee_id = o.employee_id
JOIN payments p
ON o.order_id = p.order_id
WHERE p.payment_status='Paid'
GROUP BY
    e.employee_id,
    e.first_name,
    e.last_name
ORDER BY revenue DESC
LIMIT 10;

--------------------------------------------------------------
-- 7. Top 10 Employees by Orders
--------------------------------------------------------------
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    COUNT(o.order_id) AS total_orders
FROM employees e
LEFT JOIN orders o
ON e.employee_id = o.employee_id
GROUP BY
    e.employee_id,
    e.first_name,
    e.last_name
ORDER BY total_orders DESC
LIMIT 10;

--------------------------------------------------------------
-- 8. Employees Without Orders
--------------------------------------------------------------
SELECT
    e.employee_id,
    e.first_name,
    e.last_name
FROM employees e
LEFT JOIN orders o
ON e.employee_id = o.employee_id
WHERE o.order_id IS NULL;

--------------------------------------------------------------
-- 9. Employee Revenue Ranking
--------------------------------------------------------------
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    ROUND(SUM(p.amount),2) AS revenue
FROM employees e
JOIN orders o
ON e.employee_id = o.employee_id
JOIN payments p
ON o.order_id = p.order_id
WHERE p.payment_status='Paid'
GROUP BY
    e.employee_id,
    e.first_name,
    e.last_name
ORDER BY revenue DESC;

--------------------------------------------------------------
-- 10. Employee Performance Summary
--------------------------------------------------------------
SELECT
    COUNT(DISTINCT e.employee_id) AS total_employees,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(CASE
        WHEN p.payment_status='Paid'
        THEN p.amount
        ELSE 0
    END),2) AS total_revenue
FROM employees e
LEFT JOIN orders o
ON e.employee_id=o.employee_id
LEFT JOIN payments p
ON o.order_id=p.order_id;