-- ==========================================================
-- RETAIL SALES ANALYTICS PROJECT
-- Store Analysis
-- ==========================================================

--------------------------------------------------------------
-- 1. Total Stores
--------------------------------------------------------------
SELECT COUNT(*) AS total_stores
FROM stores;

--------------------------------------------------------------
-- 2. Number of Employees in Each Store
--------------------------------------------------------------
SELECT
    s.store_name,
    COUNT(e.employee_id) AS total_employees
FROM stores s
LEFT JOIN employees e
ON s.store_id = e.store_id
GROUP BY s.store_id, s.store_name
ORDER BY total_employees DESC;

--------------------------------------------------------------
-- 3. Orders Handled by Each Store
--------------------------------------------------------------
SELECT
    s.store_name,
    COUNT(o.order_id) AS total_orders
FROM stores s
LEFT JOIN orders o
ON s.store_id = o.store_id
GROUP BY s.store_id, s.store_name
ORDER BY total_orders DESC;

--------------------------------------------------------------
-- 4. Revenue Generated by Each Store
--------------------------------------------------------------
SELECT
    s.store_name,
    ROUND(SUM(p.amount),2) AS total_revenue
FROM stores s
JOIN orders o
ON s.store_id = o.store_id
JOIN payments p
ON o.order_id = p.order_id
WHERE p.payment_status = 'Paid'
GROUP BY s.store_id, s.store_name
ORDER BY total_revenue DESC;

--------------------------------------------------------------
-- 5. Average Revenue Per Store
--------------------------------------------------------------
SELECT
    s.store_name,
    ROUND(AVG(p.amount),2) AS average_revenue
FROM stores s
JOIN orders o
ON s.store_id = o.store_id
JOIN payments p
ON o.order_id = p.order_id
WHERE p.payment_status = 'Paid'
GROUP BY s.store_id, s.store_name
ORDER BY average_revenue DESC;

--------------------------------------------------------------
-- 6. Inventory Available in Each Store
--------------------------------------------------------------
SELECT
    s.store_name,
    SUM(i.stock_quantity) AS total_stock
FROM stores s
JOIN inventory i
ON s.store_id = i.store_id
GROUP BY s.store_id, s.store_name
ORDER BY total_stock DESC;

--------------------------------------------------------------
-- 7. Inventory Value by Store
--------------------------------------------------------------
SELECT
    s.store_name,
    ROUND(SUM(i.stock_quantity * pr.cost_price),2) AS inventory_value
FROM stores s
JOIN inventory i
ON s.store_id = i.store_id
JOIN products pr
ON i.product_id = pr.product_id
GROUP BY s.store_id, s.store_name
ORDER BY inventory_value DESC;

--------------------------------------------------------------
-- 8. Total Returns by Store
--------------------------------------------------------------
SELECT
    s.store_name,
    COUNT(r.return_id) AS total_returns
FROM stores s
JOIN orders o
ON s.store_id = o.store_id
JOIN returns r
ON o.order_id = r.order_id
GROUP BY s.store_id, s.store_name
ORDER BY total_returns DESC;

--------------------------------------------------------------
-- 9. Top 10 Best Performing Stores
--------------------------------------------------------------
SELECT
    s.store_name,
    ROUND(SUM(p.amount),2) AS revenue
FROM stores s
JOIN orders o
ON s.store_id = o.store_id
JOIN payments p
ON o.order_id = p.order_id
WHERE p.payment_status='Paid'
GROUP BY s.store_id, s.store_name
ORDER BY revenue DESC
LIMIT 10;

--------------------------------------------------------------
-- 10. Store Performance Summary
--------------------------------------------------------------
SELECT
    COUNT(DISTINCT s.store_id) AS total_stores,
    COUNT(DISTINCT e.employee_id) AS total_employees,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(CASE WHEN p.payment_status='Paid' THEN p.amount ELSE 0 END),2) AS total_revenue
FROM stores s
LEFT JOIN employees e
ON s.store_id=e.store_id
LEFT JOIN orders o
ON s.store_id=o.store_id
LEFT JOIN payments p
ON o.order_id=p.order_id;